@startuml
actor "Lender" as L
actor "Borrower 1" as B1
actor "Borrower 2" as B2
participant "Mina" as M
participant "OCTA\n$10,000/8% Loan\nContract" as O
participant "Data Repository(Bank)" as D

group Deployment
L->M: Deploy OCTA\ncontract\nwith minimum\nrequired proofs
M->O: Publish
end
group Loan 1
B1->D: Transaction Data Request
D->B1: Send signed list of transactions
B1->B1: Calculate Proofs
B1->O: Request $500 Loan with Min Proofs
L->O: Approve and offer loan to Borrower 1
B1->O: Accept loan offer
O->B1: Disburse loan
end

group Loan 2
B2->D: Transaction Data Request
D->B2: Send signed list of transactions
B2->B2: Calculate Proofs
B2->O: Request $7000 Loan with Min Proofs
L->O: Request additional proofs
B2->B2: Calculate additional Proofs
B2->O: Send additional proofs
L->O: Approve and offer loan to Borrower 2
B2->O: Accept loan offer
O->B2: Disburse loan
end
@enduml
